# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      fasterxml:
        patterns:
          - "com.fasterxml.jackson.*"
      slf4j:
        patterns:
          - "org.slf4j.*"
